### ISSUE TITLE
When will the driving-specific instruction data be available?

### ISSUE THREAD

**Issue by Xiaolong-RRL** [SaFoLab-WISC/Dolphins#4]
Dear author:

thanks for your great and impressive work!

I wander when will the driving-specific instruction data and the full training progress be available? I am looking forward to it~

Best Regards～
Xiaolong

**Comment by gray311** [comment]
Thank you for being interested in our work, this is our [driving-specific data](https://drive.google.com/file/d/1gmCTyjdoiI4qTknyhatAVMDVuqX3nu4l/view?usp=sharing), and I plan to make the training code public within this month!
