### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by xiaoyisong** [SaFoLab-WISC/Dolphins#5]
how do you evaluate the performance of dolphins? 
Many demonstrations are shown in the paper, which is interesting, how to conduct automatic evaluation for each task?

**Comment by waterluy** [comment]
Could you please provide the automatic evaluation codes in [dolphins_bench,](https://huggingface.co/datasets/gray311/Dolphins-Bench/tree/main) such as how to calculate the quantitative evaluation results in your latest version of the paper?
